//Global
export const UPDATE_LOADING_SPINNER = 'UPDATE_LOADING_SPINNER';

//Players
export const LOAD_PLAYER_LIST = 'LOAD_PLAYER_LIST';
export const FILTER_PLAYER_LIST = 'FILTER_PLAYER_LIST';
export const LOAD_PLAYER = 'LOAD_PLAYER';
export const SAVE_PLAYER = 'SAVE_PLAYER';

//Competitions
export const LOAD_COMPETITION_LIST = 'LOAD_COMPETITION_LIST';
export const LOAD_COMPETITION_TEAMS = 'LOAD_COMPETITION_TEAMS';
export const LOAD_COMPETITION_TEAM_EVOLUTION = 'LOAD_COMPETITION_TEAM_EVOLUTION';