//Global
export const UPDATE_LOADING_SPINNER = 'UPDATE_LOADING_SPINNER';
export const TOAST_DASH_MESSAGE = 'TOAST_DASH_MESSAGE';
export const TOAST_DASH_CLEAR = 'TOAST_DASH_CLEAR';
export const TOAST_DASH_ERROR = 'TOAST_DASH_ERROR';

//Players
export const LOAD_PLAYER_LIST = 'LOAD_PLAYER_LIST';
export const FILTER_PLAYER_LIST = 'FILTER_PLAYER_LIST';
export const LOAD_PLAYER = 'LOAD_PLAYER';
export const SAVE_PLAYER = 'SAVE_PLAYER';

//Competitions
export const LOAD_COMPETITION_LIST = 'LOAD_COMPETITION_LIST';
export const LOAD_COMPETITION_TEAMS = 'LOAD_COMPETITION_TEAMS';
export const LOAD_COMPETITION_TEAM_EVOLUTION =
  'LOAD_COMPETITION_TEAM_EVOLUTION';
export const LOAD_MATCH_INFO = 'LOAD_MATCH_INFO';
export const SAVE_COMPETITION = 'SAVE_COMPETITION';
export const LOAD_COMPETITION = 'LOAD_COMPETITION';
export const LOAD_COMPETITION_ROUND = 'LOAD_COMPETITION_ROUND';
export const LOAD_COMPETITION_DRAW = 'LOAD_COMPETITION_DRAW';

//Teams
export const LOAD_TEAM_LIST = 'LOAD_TEAM_LIST';
export const LOAD_TEAM = 'LOAD_TEAM';
export const SAVE_TEAM = 'SAVE_TEAM';
export const CLEAR_TEAM_DATA = 'CLEAR_TEAM_DATA';

export const LOAD_TEAM_LIST_SAGAS = 'LOAD_TEAM_LIST_SAGAS';
export const LOAD_TEAM_SAGAS = 'LOAD_TEAM_SAGAS';
export const SAVE_TEAM_SAGAS = 'SAVE_TEAM_SAGAS';
